#!/usr/bin/env node

// ... Some code that will be run before the hook
console.log(process.cwd());

// GRUNT-GITHOOKS START // GRUNT-GITHOOKS END

// ... Some code that will be run after the hook... if it does not exit, that is
console.log(process.cwd());